import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
// import { UserProvider } from "./context/UserContext";
// import { SessionProvider } from "next-auth/react";

const notoSansJP = Noto_Sans_JP({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        {/* <UserProvider> */}
        <Header />
        {children}
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
